---

# http://serverfault.com/questions/638507/how-to-access-host-variable-of-a-different-host-with-ansible
# We need some facts from the install node, specifically to find address of slurm controller.
- name: grab facts from production nodes
  hosts: merope-nfs
  tasks: [ ]

- name: merope NFS servers
  hosts: merope-nfs
#  remote_user: root
#  become: yes

  roles: 
  - { role: nfs-server }

