---
nfs_kernel.shmmax: 68719476736
nfs_kernel.shmall: 4294967296
nfs_net.ipv4.tcp_timestamps: 0
nfs_net.ipv4.tcp_sack: 1
nfs_net.core.netdev_max_backlog: 250000
nfs_net.core.rmem_max: 4194304
nfs_net.core.wmem_max: 4194304
nfs_net.core.rmem_default: 4194304
nfs_net.core.wmem_default: 4194303
nfs_net.core.optmem_max: 4194304
nfs_net.ipv4.tcp_rmem: "4096 87380 4194304"
nfs_net.ipv4.tcp_low_latency: 1
nfs_vm.dirty_background_ratio: 5
nfs_vm.dirty_ratio: 10
nfs_vm.min_free_kbytes: 1048576
nfs_vm.zone_reclaim_mode: 1

