---
# Include variables and define needed variables.
#- name: Include OS-specific variables.
#  include_vars: "{{ ansible_os_family }}.yml"

# Setup/install tasks.
- include: centos6.yml
  when: (ansible_os_family == "CentOS" and ansible_distribution_major_version == "6") or
        (ansible_os_family == "RedHat" and ansible_distribution_major_version == "6")

#- include: setup-RedHat.yml
#  when: ansible_os_family == 'RedHat'

